/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "allow"
      | "allowThis"
      | "and_"
      | "asEaddress"
      | "asEbool"
      | "asEuint64"
      | "eq"
      | "fromExternal"
      | "ge"
      | "gt"
      | "isSenderAllowed"
      | "le"
      | "lt"
      | "makePubliclyDecryptable"
      | "mul"
      | "ne"
      | "not_"
      | "or_"
      | "publicDecrypt"
      | "select"
      | "sub"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "add",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allow",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowThis",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "asEaddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "asEbool", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "asEuint64",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eq",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fromExternal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSenderAllowed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makePubliclyDecryptable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "not_", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "or_",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publicDecrypt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "select",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowThis", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "and_", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asEaddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asEbool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asEuint64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eq", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fromExternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSenderAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "le", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makePubliclyDecryptable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ne", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "not_", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "or_", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "select", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub", data: BytesLike): Result;
}

export interface IFHE extends BaseContract {
  connect(runner?: ContractRunner | null): IFHE;
  waitForDeployment(): Promise<this>;

  interface: IFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  allow: TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  allowThis: TypedContractMethod<[handle: BytesLike], [void], "nonpayable">;

  and_: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  asEaddress: TypedContractMethod<[value: AddressLike], [string], "nonpayable">;

  asEbool: TypedContractMethod<[value: boolean], [string], "nonpayable">;

  asEuint64: TypedContractMethod<[value: BigNumberish], [string], "nonpayable">;

  eq: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  fromExternal: TypedContractMethod<
    [handle: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  ge: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  gt: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  isSenderAllowed: TypedContractMethod<[handle: BytesLike], [boolean], "view">;

  le: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  lt: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  makePubliclyDecryptable: TypedContractMethod<
    [handle: BytesLike],
    [void],
    "nonpayable"
  >;

  mul: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  ne: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  not_: TypedContractMethod<[value: BytesLike], [string], "nonpayable">;

  or_: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  publicDecrypt: TypedContractMethod<[handle: BytesLike], [bigint], "view">;

  select: TypedContractMethod<
    [condition: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;

  sub: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allow"
  ): TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowThis"
  ): TypedContractMethod<[handle: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "and_"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "asEaddress"
  ): TypedContractMethod<[value: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "asEbool"
  ): TypedContractMethod<[value: boolean], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "asEuint64"
  ): TypedContractMethod<[value: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "eq"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fromExternal"
  ): TypedContractMethod<
    [handle: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isSenderAllowed"
  ): TypedContractMethod<[handle: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "le"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "makePubliclyDecryptable"
  ): TypedContractMethod<[handle: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mul"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_"
  ): TypedContractMethod<[value: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "or_"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publicDecrypt"
  ): TypedContractMethod<[handle: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "select"
  ): TypedContractMethod<
    [condition: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  filters: {};
}
