/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
import type * as tron from "./tron";
export type { tron };
export type { BatchTransfer } from "./BatchTransfer";
