/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProtocolBankTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GUARDIAN_ROLE"
      | "RELAYER_ROLE"
      | "cancelEmergencyWithdraw"
      | "currentDayReleased"
      | "dailyReleaseCap"
      | "depositToHashKey"
      | "emergencyRequests"
      | "emergencyWithdrawalDelay"
      | "executeEmergencyWithdraw"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isBurnProcessed"
      | "lastReleaseResetDay"
      | "netDeposited"
      | "pause"
      | "paused"
      | "processedBurnTxs"
      | "releaseFromBurn"
      | "remainingDailyRelease"
      | "renounceRole"
      | "requestEmergencyWithdraw"
      | "revokeRole"
      | "setDailyReleaseCap"
      | "setEmergencyDelay"
      | "supportsInterface"
      | "totalDeposited"
      | "totalReleased"
      | "unpause"
      | "usdc"
      | "vaultBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyReleaseCapUpdated"
      | "DepositForMint"
      | "EmergencyDelayUpdated"
      | "EmergencyWithdrawCanceled"
      | "EmergencyWithdrawExecuted"
      | "EmergencyWithdrawRequested"
      | "Paused"
      | "ReleaseCapReset"
      | "ReleasedFromBurn"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelEmergencyWithdraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentDayReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyReleaseCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToHashKey",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawalDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeEmergencyWithdraw",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBurnProcessed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastReleaseResetDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "netDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedBurnTxs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFromBurn",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingDailyRelease",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEmergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyReleaseCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReleased",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vaultBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentDayReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyReleaseCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToHashKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawalDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBurnProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastReleaseResetDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "netDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedBurnTxs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFromBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingDailyRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDailyReleaseCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultBalance",
    data: BytesLike
  ): Result;
}

export namespace DailyReleaseCapUpdatedEvent {
  export type InputTuple = [oldCap: BigNumberish, newCap: BigNumberish];
  export type OutputTuple = [oldCap: bigint, newCap: bigint];
  export interface OutputObject {
    oldCap: bigint;
    newCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositForMintEvent {
  export type InputTuple = [
    depositor: AddressLike,
    amount: BigNumberish,
    hashKeyRecipient: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    depositor: string,
    amount: bigint,
    hashKeyRecipient: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    depositor: string;
    amount: bigint;
    hashKeyRecipient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyDelayUpdatedEvent {
  export type InputTuple = [oldDelay: BigNumberish, newDelay: BigNumberish];
  export type OutputTuple = [oldDelay: bigint, newDelay: bigint];
  export interface OutputObject {
    oldDelay: bigint;
    newDelay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawCanceledEvent {
  export type InputTuple = [requestHash: BytesLike];
  export type OutputTuple = [requestHash: string];
  export interface OutputObject {
    requestHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawExecutedEvent {
  export type InputTuple = [
    executor: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    requestHash: BytesLike
  ];
  export type OutputTuple = [
    executor: string,
    to: string,
    amount: bigint,
    requestHash: string
  ];
  export interface OutputObject {
    executor: string;
    to: string;
    amount: bigint;
    requestHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawRequestedEvent {
  export type InputTuple = [
    requester: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    requestHash: BytesLike,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    requester: string,
    to: string,
    amount: bigint,
    requestHash: string,
    unlockTime: bigint
  ];
  export interface OutputObject {
    requester: string;
    to: string;
    amount: bigint;
    requestHash: string;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseCapResetEvent {
  export type InputTuple = [day: BigNumberish, previousDayTotal: BigNumberish];
  export type OutputTuple = [day: bigint, previousDayTotal: bigint];
  export interface OutputObject {
    day: bigint;
    previousDayTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedFromBurnEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount: BigNumberish,
    burnTxHash: BytesLike,
    relayer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    amount: bigint,
    burnTxHash: string,
    relayer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
    burnTxHash: string;
    relayer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProtocolBankTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): ProtocolBankTreasury;
  waitForDeployment(): Promise<this>;

  interface: ProtocolBankTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  cancelEmergencyWithdraw: TypedContractMethod<
    [requestHash: BytesLike],
    [void],
    "nonpayable"
  >;

  currentDayReleased: TypedContractMethod<[], [bigint], "view">;

  dailyReleaseCap: TypedContractMethod<[], [bigint], "view">;

  depositToHashKey: TypedContractMethod<
    [amount: BigNumberish, hashKeyRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyRequests: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  emergencyWithdrawalDelay: TypedContractMethod<[], [bigint], "view">;

  executeEmergencyWithdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, requestHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isBurnProcessed: TypedContractMethod<
    [burnTxHash: BytesLike],
    [boolean],
    "view"
  >;

  lastReleaseResetDay: TypedContractMethod<[], [bigint], "view">;

  netDeposited: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processedBurnTxs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  releaseFromBurn: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, burnTxHash: BytesLike],
    [void],
    "nonpayable"
  >;

  remainingDailyRelease: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestEmergencyWithdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setDailyReleaseCap: TypedContractMethod<
    [newCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  setEmergencyDelay: TypedContractMethod<
    [newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalDeposited: TypedContractMethod<[], [bigint], "view">;

  totalReleased: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  vaultBalance: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelEmergencyWithdraw"
  ): TypedContractMethod<[requestHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentDayReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyReleaseCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositToHashKey"
  ): TypedContractMethod<
    [amount: BigNumberish, hashKeyRecipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyRequests"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdrawalDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeEmergencyWithdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, requestHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBurnProcessed"
  ): TypedContractMethod<[burnTxHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastReleaseResetDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "netDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processedBurnTxs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "releaseFromBurn"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, burnTxHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remainingDailyRelease"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestEmergencyWithdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDailyReleaseCap"
  ): TypedContractMethod<[newCap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEmergencyDelay"
  ): TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultBalance"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DailyReleaseCapUpdated"
  ): TypedContractEvent<
    DailyReleaseCapUpdatedEvent.InputTuple,
    DailyReleaseCapUpdatedEvent.OutputTuple,
    DailyReleaseCapUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositForMint"
  ): TypedContractEvent<
    DepositForMintEvent.InputTuple,
    DepositForMintEvent.OutputTuple,
    DepositForMintEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyDelayUpdated"
  ): TypedContractEvent<
    EmergencyDelayUpdatedEvent.InputTuple,
    EmergencyDelayUpdatedEvent.OutputTuple,
    EmergencyDelayUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawCanceled"
  ): TypedContractEvent<
    EmergencyWithdrawCanceledEvent.InputTuple,
    EmergencyWithdrawCanceledEvent.OutputTuple,
    EmergencyWithdrawCanceledEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawExecuted"
  ): TypedContractEvent<
    EmergencyWithdrawExecutedEvent.InputTuple,
    EmergencyWithdrawExecutedEvent.OutputTuple,
    EmergencyWithdrawExecutedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawRequested"
  ): TypedContractEvent<
    EmergencyWithdrawRequestedEvent.InputTuple,
    EmergencyWithdrawRequestedEvent.OutputTuple,
    EmergencyWithdrawRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseCapReset"
  ): TypedContractEvent<
    ReleaseCapResetEvent.InputTuple,
    ReleaseCapResetEvent.OutputTuple,
    ReleaseCapResetEvent.OutputObject
  >;
  getEvent(
    key: "ReleasedFromBurn"
  ): TypedContractEvent<
    ReleasedFromBurnEvent.InputTuple,
    ReleasedFromBurnEvent.OutputTuple,
    ReleasedFromBurnEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DailyReleaseCapUpdated(uint256,uint256)": TypedContractEvent<
      DailyReleaseCapUpdatedEvent.InputTuple,
      DailyReleaseCapUpdatedEvent.OutputTuple,
      DailyReleaseCapUpdatedEvent.OutputObject
    >;
    DailyReleaseCapUpdated: TypedContractEvent<
      DailyReleaseCapUpdatedEvent.InputTuple,
      DailyReleaseCapUpdatedEvent.OutputTuple,
      DailyReleaseCapUpdatedEvent.OutputObject
    >;

    "DepositForMint(address,uint256,address,uint256)": TypedContractEvent<
      DepositForMintEvent.InputTuple,
      DepositForMintEvent.OutputTuple,
      DepositForMintEvent.OutputObject
    >;
    DepositForMint: TypedContractEvent<
      DepositForMintEvent.InputTuple,
      DepositForMintEvent.OutputTuple,
      DepositForMintEvent.OutputObject
    >;

    "EmergencyDelayUpdated(uint256,uint256)": TypedContractEvent<
      EmergencyDelayUpdatedEvent.InputTuple,
      EmergencyDelayUpdatedEvent.OutputTuple,
      EmergencyDelayUpdatedEvent.OutputObject
    >;
    EmergencyDelayUpdated: TypedContractEvent<
      EmergencyDelayUpdatedEvent.InputTuple,
      EmergencyDelayUpdatedEvent.OutputTuple,
      EmergencyDelayUpdatedEvent.OutputObject
    >;

    "EmergencyWithdrawCanceled(bytes32)": TypedContractEvent<
      EmergencyWithdrawCanceledEvent.InputTuple,
      EmergencyWithdrawCanceledEvent.OutputTuple,
      EmergencyWithdrawCanceledEvent.OutputObject
    >;
    EmergencyWithdrawCanceled: TypedContractEvent<
      EmergencyWithdrawCanceledEvent.InputTuple,
      EmergencyWithdrawCanceledEvent.OutputTuple,
      EmergencyWithdrawCanceledEvent.OutputObject
    >;

    "EmergencyWithdrawExecuted(address,address,uint256,bytes32)": TypedContractEvent<
      EmergencyWithdrawExecutedEvent.InputTuple,
      EmergencyWithdrawExecutedEvent.OutputTuple,
      EmergencyWithdrawExecutedEvent.OutputObject
    >;
    EmergencyWithdrawExecuted: TypedContractEvent<
      EmergencyWithdrawExecutedEvent.InputTuple,
      EmergencyWithdrawExecutedEvent.OutputTuple,
      EmergencyWithdrawExecutedEvent.OutputObject
    >;

    "EmergencyWithdrawRequested(address,address,uint256,bytes32,uint256)": TypedContractEvent<
      EmergencyWithdrawRequestedEvent.InputTuple,
      EmergencyWithdrawRequestedEvent.OutputTuple,
      EmergencyWithdrawRequestedEvent.OutputObject
    >;
    EmergencyWithdrawRequested: TypedContractEvent<
      EmergencyWithdrawRequestedEvent.InputTuple,
      EmergencyWithdrawRequestedEvent.OutputTuple,
      EmergencyWithdrawRequestedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReleaseCapReset(uint256,uint256)": TypedContractEvent<
      ReleaseCapResetEvent.InputTuple,
      ReleaseCapResetEvent.OutputTuple,
      ReleaseCapResetEvent.OutputObject
    >;
    ReleaseCapReset: TypedContractEvent<
      ReleaseCapResetEvent.InputTuple,
      ReleaseCapResetEvent.OutputTuple,
      ReleaseCapResetEvent.OutputObject
    >;

    "ReleasedFromBurn(address,uint256,bytes32,address,uint256)": TypedContractEvent<
      ReleasedFromBurnEvent.InputTuple,
      ReleasedFromBurnEvent.OutputTuple,
      ReleasedFromBurnEvent.OutputObject
    >;
    ReleasedFromBurn: TypedContractEvent<
      ReleasedFromBurnEvent.InputTuple,
      ReleasedFromBurnEvent.OutputTuple,
      ReleasedFromBurnEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
