-- Enable real row-level security for every user-scoped table.
-- See scripts/033_enable_rls.sql for the mechanism (SET LOCAL ROLE prisma_application + app.wallet).
-- Policies are inert for the superuser connection until RLS_MODE=enforce.

ALTER TABLE a2a_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE a2a_messages FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_a2a_messages ON a2a_messages;
CREATE POLICY rls_a2a_messages ON a2a_messages FOR ALL USING (lower(from_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(from_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE acquiring_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE acquiring_orders FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_acquiring_orders ON acquiring_orders;
CREATE POLICY rls_acquiring_orders ON acquiring_orders FOR ALL USING (lower(payer_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(payer_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE agent_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_activities FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_agent_activities ON agent_activities;
CREATE POLICY rls_agent_activities ON agent_activities FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE agent_budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_budgets FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_agent_budgets ON agent_budgets;
CREATE POLICY rls_agent_budgets ON agent_budgets FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE agent_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_cards FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_agent_cards ON agent_cards;
CREATE POLICY rls_agent_cards ON agent_cards FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE agent_virtual_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_virtual_cards FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_agent_virtual_cards ON agent_virtual_cards;
CREATE POLICY rls_agent_virtual_cards ON agent_virtual_cards FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE agents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_agents ON agents;
CREATE POLICY rls_agents ON agents FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE ai_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_sessions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ai_sessions ON ai_sessions;
CREATE POLICY rls_ai_sessions ON ai_sessions FOR ALL USING (lower(wallet_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(wallet_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_api_keys ON api_keys;
CREATE POLICY rls_api_keys ON api_keys FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE asset_distributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_distributions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_asset_distributions ON asset_distributions;
CREATE POLICY rls_asset_distributions ON asset_distributions FOR ALL USING (lower(recipient_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(recipient_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE auth_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_users FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_auth_users ON auth_users;
CREATE POLICY rls_auth_users ON auth_users FOR ALL USING (lower(wallet_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(wallet_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE batch_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE batch_jobs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_batch_jobs ON batch_jobs;
CREATE POLICY rls_batch_jobs ON batch_jobs FOR ALL USING (lower(user_id) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_id) = lower(current_setting('app.wallet', true)));
ALTER TABLE batch_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE batch_payments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_batch_payments ON batch_payments;
CREATE POLICY rls_batch_payments ON batch_payments FOR ALL USING (lower(from_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(from_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE billing_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_history FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_billing_history ON billing_history;
CREATE POLICY rls_billing_history ON billing_history FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE compliance_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_checks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_compliance_checks ON compliance_checks;
CREATE POLICY rls_compliance_checks ON compliance_checks FOR ALL USING (lower(address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(address) = lower(current_setting('app.wallet', true)));
ALTER TABLE corporate_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE corporate_cards FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_corporate_cards ON corporate_cards;
CREATE POLICY rls_corporate_cards ON corporate_cards FOR ALL USING (lower(user_id) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_id) = lower(current_setting('app.wallet', true)));
ALTER TABLE cross_chain_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cross_chain_transactions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_cross_chain_transactions ON cross_chain_transactions;
CREATE POLICY rls_cross_chain_transactions ON cross_chain_transactions FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE embedded_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE embedded_wallets FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_embedded_wallets ON embedded_wallets;
CREATE POLICY rls_embedded_wallets ON embedded_wallets FOR ALL USING (lower(user_id) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_id) = lower(current_setting('app.wallet', true)));
ALTER TABLE fiat_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiat_orders FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_fiat_orders ON fiat_orders;
CREATE POLICY rls_fiat_orders ON fiat_orders FOR ALL USING (lower(user_id) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_id) = lower(current_setting('app.wallet', true)));
ALTER TABLE idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE idempotency_keys FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_idempotency_keys ON idempotency_keys;
CREATE POLICY rls_idempotency_keys ON idempotency_keys FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_invoices ON invoices;
CREATE POLICY rls_invoices ON invoices FOR ALL USING (lower(recipient_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(recipient_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ledger_entries ON ledger_entries;
CREATE POLICY rls_ledger_entries ON ledger_entries FOR ALL USING (lower(account_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(account_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE mcp_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_subscriptions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_mcp_subscriptions ON mcp_subscriptions;
CREATE POLICY rls_mcp_subscriptions ON mcp_subscriptions FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE merchants ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchants FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_merchants ON merchants;
CREATE POLICY rls_merchants ON merchants FOR ALL USING (lower(user_id) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_id) = lower(current_setting('app.wallet', true)));
ALTER TABLE monetize_api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE monetize_api_keys FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_monetize_api_keys ON monetize_api_keys;
CREATE POLICY rls_monetize_api_keys ON monetize_api_keys FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE monetize_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE monetize_configs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_monetize_configs ON monetize_configs;
CREATE POLICY rls_monetize_configs ON monetize_configs FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE monthly_fee_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_fee_summary FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_monthly_fee_summary ON monthly_fee_summary;
CREATE POLICY rls_monthly_fee_summary ON monthly_fee_summary FOR ALL USING (lower(from_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(from_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE multisig_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE multisig_transactions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_multisig_transactions ON multisig_transactions;
CREATE POLICY rls_multisig_transactions ON multisig_transactions FOR ALL USING (lower(created_by) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(created_by) = lower(current_setting('app.wallet', true)));
ALTER TABLE multisig_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE multisig_wallets FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_multisig_wallets ON multisig_wallets;
CREATE POLICY rls_multisig_wallets ON multisig_wallets FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_notification_preferences ON notification_preferences;
CREATE POLICY rls_notification_preferences ON notification_preferences FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE offramp_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE offramp_transactions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_offramp_transactions ON offramp_transactions;
CREATE POLICY rls_offramp_transactions ON offramp_transactions FOR ALL USING (lower(wallet_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(wallet_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE payment_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_channels FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payment_channels ON payment_channels;
CREATE POLICY rls_payment_channels ON payment_channels FOR ALL USING (lower(consumer_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(consumer_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE payment_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_groups FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payment_groups ON payment_groups;
CREATE POLICY rls_payment_groups ON payment_groups FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE payment_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_links FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payment_links ON payment_links;
CREATE POLICY rls_payment_links ON payment_links FOR ALL USING (lower(recipient_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(recipient_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE payment_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_logs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payment_logs ON payment_logs;
CREATE POLICY rls_payment_logs ON payment_logs FOR ALL USING (lower(from_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(from_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE payment_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_proposals FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payment_proposals ON payment_proposals;
CREATE POLICY rls_payment_proposals ON payment_proposals FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE payment_split_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_split_executions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payment_split_executions ON payment_split_executions;
CREATE POLICY rls_payment_split_executions ON payment_split_executions FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE payment_split_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_split_templates FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payment_split_templates ON payment_split_templates;
CREATE POLICY rls_payment_split_templates ON payment_split_templates FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payments ON payments;
CREATE POLICY rls_payments ON payments FOR ALL USING (lower(from_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(from_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE protocol_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE protocol_fees FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_protocol_fees ON protocol_fees;
CREATE POLICY rls_protocol_fees ON protocol_fees FOR ALL USING (lower(from_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(from_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_push_subscriptions ON push_subscriptions;
CREATE POLICY rls_push_subscriptions ON push_subscriptions FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE risk_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE risk_assessments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_risk_assessments ON risk_assessments;
CREATE POLICY rls_risk_assessments ON risk_assessments FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE scheduled_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_payments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_scheduled_payments ON scheduled_payments;
CREATE POLICY rls_scheduled_payments ON scheduled_payments FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE security_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_alerts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_security_alerts ON security_alerts;
CREATE POLICY rls_security_alerts ON security_alerts FOR ALL USING (lower(address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(address) = lower(current_setting('app.wallet', true)));
ALTER TABLE settlement_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE settlement_records FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_settlement_records ON settlement_records;
CREATE POLICY rls_settlement_records ON settlement_records FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE subscription_authorizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_authorizations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_subscription_authorizations ON subscription_authorizations;
CREATE POLICY rls_subscription_authorizations ON subscription_authorizations FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_subscriptions ON subscriptions;
CREATE POLICY rls_subscriptions ON subscriptions FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_teams ON teams;
CREATE POLICY rls_teams ON teams FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE trade_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE trade_records FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_trade_records ON trade_records;
CREATE POLICY rls_trade_records ON trade_records FOR ALL USING (lower(wallet_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(wallet_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE trading_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE trading_accounts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_trading_accounts ON trading_accounts;
CREATE POLICY rls_trading_accounts ON trading_accounts FOR ALL USING (lower(wallet_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(wallet_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE transaction_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_fees FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_transaction_fees ON transaction_fees;
CREATE POLICY rls_transaction_fees ON transaction_fees FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE usage_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_metrics FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_usage_metrics ON usage_metrics;
CREATE POLICY rls_usage_metrics ON usage_metrics FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE user_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_balances FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_user_balances ON user_balances;
CREATE POLICY rls_user_balances ON user_balances FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_subscriptions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_user_subscriptions ON user_subscriptions;
CREATE POLICY rls_user_subscriptions ON user_subscriptions FOR ALL USING (lower(user_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(user_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE user_virtual_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_virtual_cards FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_user_virtual_cards ON user_virtual_cards;
CREATE POLICY rls_user_virtual_cards ON user_virtual_cards FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendors FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_vendors ON vendors;
CREATE POLICY rls_vendors ON vendors FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE webhooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhooks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_webhooks ON webhooks;
CREATE POLICY rls_webhooks ON webhooks FOR ALL USING (lower(owner_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(owner_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE x402_authorizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE x402_authorizations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_x402_authorizations ON x402_authorizations;
CREATE POLICY rls_x402_authorizations ON x402_authorizations FOR ALL USING (lower(from_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(from_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE x402_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE x402_settlements FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_x402_settlements ON x402_settlements;
CREATE POLICY rls_x402_settlements ON x402_settlements FOR ALL USING (lower(from_address) = lower(current_setting('app.wallet', true))) WITH CHECK (lower(from_address) = lower(current_setting('app.wallet', true)));
ALTER TABLE api_key_usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_key_usage_logs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_api_key_usage_logs ON api_key_usage_logs;
CREATE POLICY rls_api_key_usage_logs ON api_key_usage_logs FOR ALL USING (EXISTS (SELECT 1 FROM api_keys p WHERE p.id = api_key_usage_logs.api_key_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM api_keys p WHERE p.id = api_key_usage_logs.api_key_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE agent_webhook_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_webhook_deliveries FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_agent_webhook_deliveries ON agent_webhook_deliveries;
CREATE POLICY rls_agent_webhook_deliveries ON agent_webhook_deliveries FOR ALL USING (EXISTS (SELECT 1 FROM agents p WHERE p.id = agent_webhook_deliveries.agent_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM agents p WHERE p.id = agent_webhook_deliveries.agent_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE batch_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE batch_chunks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_batch_chunks ON batch_chunks;
CREATE POLICY rls_batch_chunks ON batch_chunks FOR ALL USING (EXISTS (SELECT 1 FROM batch_jobs p WHERE p.id = batch_chunks.job_id AND lower(p.user_id) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM batch_jobs p WHERE p.id = batch_chunks.job_id AND lower(p.user_id) = lower(current_setting('app.wallet', true))));
ALTER TABLE batch_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE batch_items FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_batch_items ON batch_items;
CREATE POLICY rls_batch_items ON batch_items FOR ALL USING (EXISTS (SELECT 1 FROM batch_payments p WHERE p.batch_id = batch_items.batch_id AND lower(p.from_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM batch_payments p WHERE p.batch_id = batch_items.batch_id AND lower(p.from_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE card_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE card_transactions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_card_transactions ON card_transactions;
CREATE POLICY rls_card_transactions ON card_transactions FOR ALL USING (EXISTS (SELECT 1 FROM corporate_cards p WHERE p.id = card_transactions.card_id AND lower(p.user_id) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM corporate_cards p WHERE p.id = card_transactions.card_id AND lower(p.user_id) = lower(current_setting('app.wallet', true))));
ALTER TABLE channel_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_payments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_channel_payments ON channel_payments;
CREATE POLICY rls_channel_payments ON channel_payments FOR ALL USING (EXISTS (SELECT 1 FROM payment_channels p WHERE p.id = channel_payments.channel_id AND lower(p.consumer_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM payment_channels p WHERE p.id = channel_payments.channel_id AND lower(p.consumer_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE cross_chain_state_transitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cross_chain_state_transitions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_cross_chain_state_transitions ON cross_chain_state_transitions;
CREATE POLICY rls_cross_chain_state_transitions ON cross_chain_state_transitions FOR ALL USING (EXISTS (SELECT 1 FROM cross_chain_transactions p WHERE p.id = cross_chain_state_transitions.transaction_id AND lower(p.user_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM cross_chain_transactions p WHERE p.id = cross_chain_state_transitions.transaction_id AND lower(p.user_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE merchant_api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_api_keys FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_merchant_api_keys ON merchant_api_keys;
CREATE POLICY rls_merchant_api_keys ON merchant_api_keys FOR ALL USING (EXISTS (SELECT 1 FROM merchants p WHERE p.id = merchant_api_keys.merchant_id AND lower(p.user_id) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM merchants p WHERE p.id = merchant_api_keys.merchant_id AND lower(p.user_id) = lower(current_setting('app.wallet', true))));
ALTER TABLE merchant_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_balances FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_merchant_balances ON merchant_balances;
CREATE POLICY rls_merchant_balances ON merchant_balances FOR ALL USING (EXISTS (SELECT 1 FROM merchants p WHERE p.id = merchant_balances.merchant_id AND lower(p.user_id) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM merchants p WHERE p.id = merchant_balances.merchant_id AND lower(p.user_id) = lower(current_setting('app.wallet', true))));
ALTER TABLE multisig_confirmations ENABLE ROW LEVEL SECURITY;
ALTER TABLE multisig_confirmations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_multisig_confirmations ON multisig_confirmations;
CREATE POLICY rls_multisig_confirmations ON multisig_confirmations FOR ALL USING (EXISTS (SELECT 1 FROM multisig_transactions p WHERE p.id = multisig_confirmations.transaction_id AND lower(p.created_by) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM multisig_transactions p WHERE p.id = multisig_confirmations.transaction_id AND lower(p.created_by) = lower(current_setting('app.wallet', true))));
ALTER TABLE payment_link_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_link_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_payment_link_events ON payment_link_events;
CREATE POLICY rls_payment_link_events ON payment_link_events FOR ALL USING (EXISTS (SELECT 1 FROM payment_links p WHERE p.link_id = payment_link_events.link_id AND lower(p.recipient_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM payment_links p WHERE p.link_id = payment_link_events.link_id AND lower(p.recipient_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE scheduled_payment_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_payment_logs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_scheduled_payment_logs ON scheduled_payment_logs;
CREATE POLICY rls_scheduled_payment_logs ON scheduled_payment_logs FOR ALL USING (EXISTS (SELECT 1 FROM scheduled_payments p WHERE p.id = scheduled_payment_logs.scheduled_payment_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM scheduled_payments p WHERE p.id = scheduled_payment_logs.scheduled_payment_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE subscription_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_payments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_subscription_payments ON subscription_payments;
CREATE POLICY rls_subscription_payments ON subscription_payments FOR ALL USING (EXISTS (SELECT 1 FROM subscriptions p WHERE p.id = subscription_payments.subscription_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM subscriptions p WHERE p.id = subscription_payments.subscription_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE team_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_audit_logs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_team_audit_logs ON team_audit_logs;
CREATE POLICY rls_team_audit_logs ON team_audit_logs FOR ALL USING (EXISTS (SELECT 1 FROM teams p WHERE p.id = team_audit_logs.team_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM teams p WHERE p.id = team_audit_logs.team_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_team_members ON team_members;
CREATE POLICY rls_team_members ON team_members FOR ALL USING (EXISTS (SELECT 1 FROM teams p WHERE p.id = team_members.team_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM teams p WHERE p.id = team_members.team_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE vendor_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_addresses FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_vendor_addresses ON vendor_addresses;
CREATE POLICY rls_vendor_addresses ON vendor_addresses FOR ALL USING (EXISTS (SELECT 1 FROM vendors p WHERE p.id = vendor_addresses.vendor_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM vendors p WHERE p.id = vendor_addresses.vendor_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true))));
ALTER TABLE webhook_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_deliveries FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_webhook_deliveries ON webhook_deliveries;
CREATE POLICY rls_webhook_deliveries ON webhook_deliveries FOR ALL USING (EXISTS (SELECT 1 FROM webhooks p WHERE p.id = webhook_deliveries.webhook_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true)))) WITH CHECK (EXISTS (SELECT 1 FROM webhooks p WHERE p.id = webhook_deliveries.webhook_id AND lower(p.owner_address) = lower(current_setting('app.wallet', true))));
