/**
 * Provision the asset-distribution wallet.
 *
 * Generates a dedicated distributor wallet (if none is configured yet), stores
 * it in .env.local, then funds it from the relayer with a little Sepolia ETH
 * (gas) and USDC (the asset to hand out in tests).
 *
 *   $env:DOTENV_CONFIG_PATH='.env.local'; npx tsx -r dotenv/config scripts/setup-asset-distributor.ts
 */
import { appendFileSync } from "node:fs"
import { Contract, JsonRpcProvider, Wallet, formatEther, formatUnits, parseEther, parseUnits } from "ethers"
import { getTokenAddress } from "@/lib/erc3009"

const CHAIN_ID = 11155111
const RPC = process.env.SEPOLIA_RPC_URL ?? "https://ethereum-sepolia-rpc.publicnode.com"
const USDC = getTokenAddress(CHAIN_ID, "USDC")!
const ETH_TOPUP = "0.003"
const USDC_TOPUP = "0.05"

async function main() {
  const envPath = ".env.local"

  let distributorKey = process.env.ASSET_DISTRIBUTOR_PRIVATE_KEY
  if (!distributorKey) {
    const wallet = Wallet.createRandom()
    distributorKey = wallet.privateKey
    const block =
      `\n# Asset distribution wallet (generated by scripts/setup-asset-distributor.ts)\n` +
      `ASSET_DISTRIBUTOR_ADDRESS=${wallet.address}\n` +
      `ASSET_DISTRIBUTOR_PRIVATE_KEY=${wallet.privateKey}\n`
    appendFileSync(envPath, block, "utf8")
    process.env.ASSET_DISTRIBUTOR_ADDRESS = wallet.address
    process.env.ASSET_DISTRIBUTOR_PRIVATE_KEY = distributorKey
    console.log(`generated distributor wallet ${wallet.address} (stored in .env.local)`)
  } else {
    console.log(`using existing distributor ${new Wallet(distributorKey).address}`)
  }

  const relayerPk = process.env.RELAYER_PRIVATE_KEY
  if (!relayerPk) throw new Error("RELAYER_PRIVATE_KEY missing")
  const provider = new JsonRpcProvider(RPC, undefined, { staticNetwork: true })
  const relayer = new Wallet(relayerPk, provider)
  const distributor = new Wallet(distributorKey, provider)

  const usdc = new Contract(USDC, ["function transfer(address,uint256) returns (bool)", "function balanceOf(address) view returns (uint256)"], relayer)

  const ethBal = await provider.getBalance(distributor.address)
  const usdcBal = (await usdc.balanceOf(distributor.address)) as bigint
  console.log(`distributor balances: ${formatEther(ethBal)} ETH · ${formatUnits(usdcBal, 6)} USDC`)

  if (ethBal < parseEther("0.001")) {
    const tx = await relayer.sendTransaction({ to: distributor.address, value: parseEther(ETH_TOPUP) })
    await tx.wait()
    console.log(`funded ${ETH_TOPUP} Sepolia ETH → ${tx.hash}`)
  }
  if (usdcBal < parseUnits(USDC_TOPUP, 6)) {
    const tx = await usdc.transfer(distributor.address, parseUnits(USDC_TOPUP, 6))
    await tx.wait()
    console.log(`funded ${USDC_TOPUP} USDC → ${tx.hash}`)
  }

  const finalEth = await provider.getBalance(distributor.address)
  const finalUsdc = (await usdc.balanceOf(distributor.address)) as bigint
  console.log(`ready: ${distributor.address} · ${formatEther(finalEth)} ETH · ${formatUnits(finalUsdc, 6)} USDC`)
  process.exit(0)
}

main().catch((error) => {
  console.error("FATAL", error instanceof Error ? error.message : String(error))
  process.exit(1)
})
