/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acl"
      | "add"
      | "allow"
      | "allowThis"
      | "and_"
      | "asEaddress"
      | "asEbool"
      | "asEuint64"
      | "eq"
      | "fromExternal"
      | "ge"
      | "gt"
      | "handleCount"
      | "isPubliclyDecryptable"
      | "isSenderAllowed"
      | "le"
      | "lt"
      | "makePubliclyDecryptable"
      | "mul"
      | "ne"
      | "not_"
      | "or_"
      | "plaintextValues"
      | "publicDecrypt"
      | "revealPlaintext"
      | "select"
      | "sub"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MockACLGrant"
      | "MockDecryptRequest"
      | "MockEncrypt"
      | "MockOperation"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acl",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allow",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowThis",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "asEaddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "asEbool", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "asEuint64",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eq",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fromExternal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPubliclyDecryptable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSenderAllowed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makePubliclyDecryptable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "not_", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "or_",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "plaintextValues",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publicDecrypt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealPlaintext",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "select",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "acl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowThis", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "and_", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asEaddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asEbool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asEuint64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eq", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fromExternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPubliclyDecryptable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSenderAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "le", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makePubliclyDecryptable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ne", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "not_", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "or_", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "plaintextValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealPlaintext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "select", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub", data: BytesLike): Result;
}

export namespace MockACLGrantEvent {
  export type InputTuple = [handle: BytesLike, account: AddressLike];
  export type OutputTuple = [handle: string, account: string];
  export interface OutputObject {
    handle: string;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MockDecryptRequestEvent {
  export type InputTuple = [handle: BytesLike, value: BigNumberish];
  export type OutputTuple = [handle: string, value: bigint];
  export interface OutputObject {
    handle: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MockEncryptEvent {
  export type InputTuple = [handle: BytesLike, value: BigNumberish];
  export type OutputTuple = [handle: string, value: bigint];
  export interface OutputObject {
    handle: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MockOperationEvent {
  export type InputTuple = [op: string, result: BytesLike, value: BigNumberish];
  export type OutputTuple = [op: string, result: string, value: bigint];
  export interface OutputObject {
    op: string;
    result: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockFHE extends BaseContract {
  connect(runner?: ContractRunner | null): MockFHE;
  waitForDeployment(): Promise<this>;

  interface: MockFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acl: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  add: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  allow: TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  allowThis: TypedContractMethod<[handle: BytesLike], [void], "nonpayable">;

  and_: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  asEaddress: TypedContractMethod<[value: AddressLike], [string], "nonpayable">;

  asEbool: TypedContractMethod<[value: boolean], [string], "nonpayable">;

  asEuint64: TypedContractMethod<[value: BigNumberish], [string], "nonpayable">;

  eq: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  fromExternal: TypedContractMethod<
    [handle: BytesLike, arg1: BytesLike],
    [string],
    "nonpayable"
  >;

  ge: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  gt: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  handleCount: TypedContractMethod<[], [bigint], "view">;

  isPubliclyDecryptable: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  isSenderAllowed: TypedContractMethod<[handle: BytesLike], [boolean], "view">;

  le: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  lt: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  makePubliclyDecryptable: TypedContractMethod<
    [handle: BytesLike],
    [void],
    "nonpayable"
  >;

  mul: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  ne: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  not_: TypedContractMethod<[value: BytesLike], [string], "nonpayable">;

  or_: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  plaintextValues: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  publicDecrypt: TypedContractMethod<[handle: BytesLike], [bigint], "view">;

  revealPlaintext: TypedContractMethod<[handle: BytesLike], [bigint], "view">;

  select: TypedContractMethod<
    [condition: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;

  sub: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acl"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allow"
  ): TypedContractMethod<
    [handle: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowThis"
  ): TypedContractMethod<[handle: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "and_"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "asEaddress"
  ): TypedContractMethod<[value: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "asEbool"
  ): TypedContractMethod<[value: boolean], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "asEuint64"
  ): TypedContractMethod<[value: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "eq"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fromExternal"
  ): TypedContractMethod<
    [handle: BytesLike, arg1: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPubliclyDecryptable"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSenderAllowed"
  ): TypedContractMethod<[handle: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "le"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "makePubliclyDecryptable"
  ): TypedContractMethod<[handle: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mul"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_"
  ): TypedContractMethod<[value: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "or_"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "plaintextValues"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "publicDecrypt"
  ): TypedContractMethod<[handle: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealPlaintext"
  ): TypedContractMethod<[handle: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "select"
  ): TypedContractMethod<
    [condition: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "MockACLGrant"
  ): TypedContractEvent<
    MockACLGrantEvent.InputTuple,
    MockACLGrantEvent.OutputTuple,
    MockACLGrantEvent.OutputObject
  >;
  getEvent(
    key: "MockDecryptRequest"
  ): TypedContractEvent<
    MockDecryptRequestEvent.InputTuple,
    MockDecryptRequestEvent.OutputTuple,
    MockDecryptRequestEvent.OutputObject
  >;
  getEvent(
    key: "MockEncrypt"
  ): TypedContractEvent<
    MockEncryptEvent.InputTuple,
    MockEncryptEvent.OutputTuple,
    MockEncryptEvent.OutputObject
  >;
  getEvent(
    key: "MockOperation"
  ): TypedContractEvent<
    MockOperationEvent.InputTuple,
    MockOperationEvent.OutputTuple,
    MockOperationEvent.OutputObject
  >;

  filters: {
    "MockACLGrant(bytes32,address)": TypedContractEvent<
      MockACLGrantEvent.InputTuple,
      MockACLGrantEvent.OutputTuple,
      MockACLGrantEvent.OutputObject
    >;
    MockACLGrant: TypedContractEvent<
      MockACLGrantEvent.InputTuple,
      MockACLGrantEvent.OutputTuple,
      MockACLGrantEvent.OutputObject
    >;

    "MockDecryptRequest(bytes32,uint256)": TypedContractEvent<
      MockDecryptRequestEvent.InputTuple,
      MockDecryptRequestEvent.OutputTuple,
      MockDecryptRequestEvent.OutputObject
    >;
    MockDecryptRequest: TypedContractEvent<
      MockDecryptRequestEvent.InputTuple,
      MockDecryptRequestEvent.OutputTuple,
      MockDecryptRequestEvent.OutputObject
    >;

    "MockEncrypt(bytes32,uint256)": TypedContractEvent<
      MockEncryptEvent.InputTuple,
      MockEncryptEvent.OutputTuple,
      MockEncryptEvent.OutputObject
    >;
    MockEncrypt: TypedContractEvent<
      MockEncryptEvent.InputTuple,
      MockEncryptEvent.OutputTuple,
      MockEncryptEvent.OutputObject
    >;

    "MockOperation(string,bytes32,uint256)": TypedContractEvent<
      MockOperationEvent.InputTuple,
      MockOperationEvent.OutputTuple,
      MockOperationEvent.OutputObject
    >;
    MockOperation: TypedContractEvent<
      MockOperationEvent.InputTuple,
      MockOperationEvent.OutputTuple,
      MockOperationEvent.OutputObject
    >;
  };
}
