/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IFHE, IFHEInterface } from "../../../contracts/fhe/IFHE";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "add",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "allow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "allowThis",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "and_",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "value",
        type: "address",
      },
    ],
    name: "asEaddress",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "value",
        type: "bool",
      },
    ],
    name: "asEbool",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "value",
        type: "uint64",
      },
    ],
    name: "asEuint64",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "eq",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "inputProof",
        type: "bytes",
      },
    ],
    name: "fromExternal",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "ge",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "gt",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "isSenderAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "le",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "lt",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "makePubliclyDecryptable",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "mul",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "ne",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "value",
        type: "bytes32",
      },
    ],
    name: "not_",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "or_",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
    ],
    name: "publicDecrypt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "condition",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "ifTrue",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "ifFalse",
        type: "bytes32",
      },
    ],
    name: "select",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
    ],
    name: "sub",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFHE__factory {
  static readonly abi = _abi;
  static createInterface(): IFHEInterface {
    return new Interface(_abi) as IFHEInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFHE {
    return new Contract(address, _abi, runner) as unknown as IFHE;
  }
}
